
```{r,  results="hide"}
library(tidyverse)# Tidying up the data, Version 2.0.0
library(ggplot2) # Creating graphs, Version 3.5.1
library(plyr) # Tidying up data, Version 1.8.9
library(dplyr) #Tidying up data, Version 1.1.4
library(readr) # Loading text files, Version 2.1.5
library(readxl) # Loading excel files, Version 1.4.4
library(ggpubr) # Adding statistics in plots, Version 0.6.0 
library(stringi) # String selection tool, Version 1.8.4 
library(tidyr) # Tidying up the data, Version 1.3.1
library(reshape2) # Reshaping the data and infer statistics, Version 1.4.4
library(stringi) # String manipulation though regular expression, Version 1.8.2
library(parallel) # Parallel proscessing, Version 4.4.2
library(RColorBrewer) #
library(ggvenn)
library(gridExtra)
library(Biostrings)
library(compositions)
library(vegan)

```
Differential abundance
Load the tables
```{r,  results="hide"}
set.seed(01122025)
ASVtaxonomy=read.csv(file.path("../InputData", "16S_ASV_Table_LTE_three_years.csv"))
ASVtaxonomy=select(ASVtaxonomy, ASV, everything())
#Keep the taxonomy of the ASV table
ASVtaxonomy=ASVtaxonomy[,c(1:10)]

for(i in 1:nrow( ASVtaxonomy)){
  for(j in 1:ncol( ASVtaxonomy)){
    if( is.na( ASVtaxonomy[i,j])==T){
      ASVtaxonomy[i,j]=ASVtaxonomy[i,(j-1)]
  }
}  
}

ASVtable1= read.csv(file.path("../InputData", "16SMLERarefied_table.csv"), row.names = "X")
Mean_abundances=as.data.frame(
  apply(ASVtable1, 2, function(x) mean(x)))
Frequencies=as.data.frame(
  apply(ASVtable1, 2, function(x) sum(x>0))
)
metadata=read.csv(file.path("../InputData", "metadata1.csv"))%>%na.omit()
metadata$ID=metadata$Sample
metadata$Soil_Type[metadata$Soil_Type=="RAS"]="BS"
```


Generate metadata from the sample names
Convert Tillage and Fertilization intensity (Int) to numerical values (0,1)

```{r,  results="hide"}
metadata$Tillage2=metadata$Tillage
metadata$Tillage2[metadata$Tillage2=="CT"]=0
metadata$Tillage2[metadata$Tillage2=="MP"]=1
metadata$Tillage2=as.numeric(metadata$Tillage2)
metadata$Group=paste0(metadata$Soil_Type, "|", metadata$Year)
```
Set the multiple logistic regression
```{r,  results="hide"}

multiple_glm= function(x){
   

cl1=as.numeric( clr(x+1))
  Table_glm=glm(file1$Tillage2~ cl1, family=binomial(link="logit"))
  file2=anova(Table_glm, test = "Chisq")
  FC1=dcast(data.frame(T=file1$Tillage, A=x), T~., value.var = "A",  mean)
  FC2=log2((FC1[2,2]+1)/(FC1[1,2]+1))
  file3=data.frame(coeff=(Table_glm$coefficients[2]), p=file2$`Pr(>Chi)`[2], FC=FC2, Mean=mean(x))
  
  return(file3)
}
```

```{r}
comparison_list=list()
for (i in unique(metadata$Group)){
  print(i)
  file1=filter(metadata, Group==paste0(i) )
  input1=(as.data.frame(ASVtable1[file1$ID,]))
  input2=as.data.frame( apply(input1, 2, function (x) sum(x>0)))
  colnames(input2)<-"Count"
  input2=filter(input2, Count>3)
  input3=as.data.frame(( input1[file1$ID,rownames(input2)]))
  multiple_glms_2020_ASVs= apply(input3,2, function(x) multiple_glm(x))
  multiple_glms_ASVs_df <- as.data.frame(do.call(rbind, multiple_glms_2020_ASVs))
  multiple_glms_ASVs_df[is.na(multiple_glms_ASVs_df)]<-1
  multiple_glms_ASVs_df$padj=p.adjust(multiple_glms_ASVs_df$p, method="BH")
  multiple_glms_ASVs_df=filter(multiple_glms_ASVs_df)%>%mutate(
   Year=unique(file1$Year ),Soil_Type= unique( file1$Soil_Type))
  comparison_list=rbind(multiple_glms_ASVs_df%>%rownames_to_column(var="ASV"),comparison_list)
  
}
```

```{r}
comparison_list2=filter(full_join( comparison_list, ASVtaxonomy ), padj<0.05)
set3_colors <- brewer.pal(12,"Set3")
additional_colors <- c("white","black","grey")
my_palette <- c(set3_colors, additional_colors)

comparison_list2$Year <- factor(comparison_list2$Year, levels = sort(unique(comparison_list2$Year)))

plotPhylum= ggplot(comparison_list2, aes(x=log10(100*(Mean)/15349), y=FC, fill=tax.Phylum)) +
  geom_point(shape=21, size=5) +
  facet_grid(Year ~ Soil_Type, scales = "free") +
  scale_fill_manual(values=my_palette, name="ASV taxonomy (phylum level)") +
  
  theme_bw() +
  theme(strip.background=element_rect(fill="white", colour="black")) +
  theme(strip.text=element_text(colour="black", size=25)) +
  
  theme(axis.text.y=element_text(size=25,colour="black")) +
  theme(axis.text.x=element_text(size=25,colour="black")) +
  theme(axis.title.x=element_text(size=25,colour="black")) +

  theme(legend.text=element_text(size=25,colour="black")) + 
  theme(legend.title=element_text(size=25,colour="black")) + 
  theme(legend.position="right", axis.title.y=element_text(size=25,colour="black")) + 
  theme(legend.key.size=unit(2,"cm")) +

  ylab(expression("Log2 FC")) +
  xlab(expression("Mean Log10 RA")) + geom_hline(yintercept = 0, linetype=2)

png(filename = "Fig2_RespondersPhylum_revised.png", height = 6000,
    width = 5500, res=350)
print(plotPhylum) 
dev.off()


```

```{r}
```
Select the taxonomy of samples 
```{r}
Taxonomy=filter(ASVtaxonomy, ASV%in%c(unique(comparison_list$ASV)))
comparison_list2=filter(as.data.frame(comparison_list)%>%full_join(Taxonomy), padj<0.05)
```

````{r}  
write.csv(file = file.path("../OutputData", "TableS3_RespondersPlot.csv_revised"), comparison_list2)
````

````{r}
sequences1=Biostrings::DNAStringSet( ASVtaxonomy$Sequence)
names(sequences1)=ASVtaxonomy$ASV
writeXStringSet( sequences1, filepath = paste0("../OutputData", "/ASV.fasta"),  format = "fasta")
````

Plot the results of the venn diagramms

```{r,  results="hide"}
# Year 2019
BS_pos_resp_2019 <- comparison_list2 %>% filter(Soil_Type == "BS", coeff > 0, Year==2019)
BS_neg_resp_2019 <- comparison_list2 %>% filter(Soil_Type == "BS", coeff < 0, Year==2019)
RH_pos_resp_2019 <- comparison_list2 %>% filter(Soil_Type == "RH", coeff > 0, Year==2019)
RH_neg_resp_2019 <- comparison_list2 %>% filter(Soil_Type == "RH", coeff < 0, Year==2019)

data_pos_2019 <- list(
     "BS" = BS_pos_resp_2019$ASV
    ,"RH" = RH_pos_resp_2019$ASV
)

data_neg_2019 <- list(
     "BS" = BS_neg_resp_2019$ASV
    ,"RH" = RH_neg_resp_2019$ASV
)

plot_pos_2019 <- ggvenn(data_pos_2019, 
  c("BS", "RH"),set_name_size=4,text_size=4) + 
  theme(plot.margin = unit(c(1, 1, 1, 1), "cm"))

plot_neg_2019 <- ggvenn(data_neg_2019, 
  c("BS", "RH"),set_name_size=4,text_size=4) +
  theme(plot.margin = unit(c(1, 1, 1, 1), "cm"))

plot_2019 <- ggarrange(plot_pos_2019, plot_neg_2019, ncol=2, labels=c("MP-responders (positive)", "CT-responders (negative)"), font.label=list(size=14, face="bold"))

# Year 2020
BS_pos_resp_2020 <- comparison_list2 %>% filter(Soil_Type == "BS", coeff > 0, Year==2020)
BS_neg_resp_2020 <- comparison_list2 %>% filter(Soil_Type == "BS", coeff < 0, Year==2020)
RH_pos_resp_2020 <- comparison_list2 %>% filter(Soil_Type == "RH", coeff > 0, Year==2020)
RH_neg_resp_2020 <- comparison_list2 %>% filter(Soil_Type == "RH", coeff < 0, Year==2020)

data_pos_2020 <- list(
     "BS" = BS_pos_resp_2020$ASV
    ,"RH" = RH_pos_resp_2020$ASV
)

data_neg_2020 <- list(
     "BS" = BS_neg_resp_2020$ASV
    ,"RH" = RH_neg_resp_2020$ASV
)

plot_pos_2020 <- ggvenn(data_pos_2020, 
  c("BS", "RH"),set_name_size=4,text_size=4) +
  theme(plot.margin = unit(c(1, 1, 1, 1), "cm"))

plot_neg_2020 <- ggvenn(data_neg_2020, 
  c("BS", "RH"),set_name_size=4,text_size=4) +
  theme(plot.margin = unit(c(1, 1, 1, 1), "cm"))

plot_2020 <- ggarrange(plot_pos_2020, plot_neg_2020, ncol=2, labels=c("MP-responders (positive)", "CT-responders (negative)"), font.label=list(size=14, face="bold"))

# Year 2021
BS_pos_resp_2021 <- comparison_list2 %>% filter(Soil_Type == "BS", coeff > 0, Year==2021)
BS_neg_resp_2021 <- comparison_list2 %>% filter(Soil_Type == "BS", coeff < 0, Year==2021)
RH_pos_resp_2021 <- comparison_list2 %>% filter(Soil_Type == "RH", coeff > 0, Year==2021)
RH_neg_resp_2021 <- comparison_list2 %>% filter(Soil_Type == "RH", coeff < 0, Year==2021)


data_pos_2021 <- list(
     "BS" = BS_pos_resp_2021$ASV
    ,"RH" = RH_pos_resp_2021$ASV
)

data_neg_2021 <- list(
     "BS" = BS_neg_resp_2021$ASV
    ,"RH" = RH_neg_resp_2021$ASV
)

plot_pos_2021 <- ggvenn(data_pos_2021, 
  c("BS", "RH"),set_name_size=4,text_size =4) +
  theme(plot.margin = unit(c(1, 1, 1, 1), "cm"))

plot_neg_2021 <- ggvenn(data_neg_2021, 
  c("BS", "RH"),set_name_size=4,text_size=4) +
  theme(plot.margin = unit(c(1, 1, 1, 1), "cm"))

plot_2021 <- ggarrange(plot_pos_2021, plot_neg_2021, ncol=2, labels=c("MP-responders (positive)", "CT-responders (negative)"), font.label=list(size=14, face="bold"))

plotVenn <- ggarrange(plot_2019, plot_2020, plot_2021, nrow=3, labels=c("2019", "2020", "2021"), font.label=list(size=16, face="bold"))

dir.create(file.path("../FigS4_VennDiagrams"), showWarnings = FALSE)
png(filename = file.path("../FigS4_VennDiagrams", "FigS4_VennDiagrams.png"), height=3000, width=2750, res=300)
print(plotVenn) 
dev.off()

data_pos_BS <- list(
     "2019" = BS_pos_resp_2019$ASV,
    "2020" = BS_pos_resp_2020$ASV,
    "2021" = BS_pos_resp_2021$ASV
)

data_pos_RH <- list(
     "2019" = RH_pos_resp_2019$ASV,
    "2020" = RH_pos_resp_2020$ASV,
    "2021" = RH_pos_resp_2021$ASV
)


data_neg_BS <- list(
     "2019" = BS_neg_resp_2019$ASV,
    "2020" = BS_neg_resp_2020$ASV,
    "2021" = BS_neg_resp_2021$ASV
)
data_neg_RH <- list(
     "2019" = RH_neg_resp_2019$ASV,
    "2020" = RH_neg_resp_2020$ASV,
    "2021" = RH_neg_resp_2021$ASV
)
```

```{r}
plot_pos_BS= ggvenn(data_pos_BS, 
       c("2019", "2020","2021"),set_name_size=4,text_size=4) +
    theme(plot.margin = unit(c(1, 1, 1, 1), "cm"))

plot_pos_RH= ggvenn(data_pos_RH, 
       c("2019", "2020","2021"),set_name_size=4,text_size=4) +
    theme(plot.margin = unit(c(1, 1, 1, 1), "cm"))
plot_neg_BS= ggvenn(data_neg_BS, 
       c("2019", "2020","2021"),set_name_size=4,text_size=4) +
    theme(plot.margin = unit(c(1, 1, 1, 1), "cm"))

plot_neg_RH= ggvenn(data_neg_RH, 
       c("2019", "2020","2021"),set_name_size=4,text_size=4) +
    theme(plot.margin = unit(c(1, 1, 1, 1), "cm"))


plots_common=ggarrange(plot_pos_BS,plot_pos_RH,
  plot_neg_BS,plot_neg_RH, labels = c("MP-responders (positive) BS",
                                      "MP-responders (positive) RH",
                                      "CT-responders (negative) BS",
                                      "CT-responders (negative) RH"))

```

```{r}
dir.create(file.path("../FigS5_VennDiagrams"), showWarnings = FALSE)

png(filename = "../FigS5_VennDiagrams/SI_Venns_common_in_three_years.png", height = 3000, width = 4000, res=300)
print(plots_common) 
dev.off()
```

````{r}
perm_list=list()
for (i in unique(metadata$Group)){
  file1=filter(metadata, Group==paste0(i) )
  input1=(as.data.frame(ASVtable1[file1$ID,]))
  input1=apply(input1, 1, function (x) 100*x/sum(x))%>%t()
input2=data.frame(RA= apply(input1, 2, function (x) mean(x)))
input2=input2[order(input2$RA,decreasing =T),,drop=F]
input2=input2[1:50,,drop=F]
dist1=vegdist(input1, method = "bray")
dist2=vegdist(input1[,rownames(input2)], method = "bray")

perm1=as.data.frame(
  adonis2(dist1~Tillage*Int, data = file1, method = "bray", permutations = 99999, by="terms")
  )%>%na.omit()%>%rownames_to_column(var="Var")%>%mutate(Soil_Type=
 unique(file1$Soil_Type),
 Year=
 unique(file1$Year),Type="Full Community")

perm2=as.data.frame(
  adonis2(dist2~Tillage*Int, data = file1, method = "bray", permutations = 99999, by="terms")
  )%>%na.omit()%>%rownames_to_column(var="Var")%>%mutate(Soil_Type=
 unique(file1$Soil_Type),
 Year=
 unique(file1$Year),
                                                         Type="Dominant Fraction")

perm_list=rbind(perm1,perm_list)
perm_list=rbind(perm2,perm_list)
print(i)
}
perm_list$Variable=gsub("Tillage", "CT vs MP Tillage", 
                        gsub("Int",
  "Ext. vs Int. N-Fert.",
  gsub(
       "Tillage:Int",
                        "interaction effect",perm_list$Var)
))
perm_list$Variable=gsub(
       "interaction effect",
                        "Interaction effect",perm_list$Variable)

perm_list$padj=p.adjust(perm_list$`Pr(>F)`, method = "BH")

perm_list$padj2=perm_list$padj
perm_list$padj2[perm_list$padj>0.05]=""
perm_list$padj2[perm_list$padj<0.05]="*"
perm_list$padj2[perm_list$padj<0.01]="**"
perm_list$padj2[perm_list$padj<0.001]="***"
perm_list$padj2[perm_list$padj<0.0001]="****"
perm_list$Type=factor(perm_list$Type,
                      level=c("Full Community",
                              "Dominant Fraction" ))

perm_list$Type=factor(perm_list$Type,
                      level=c("Full Community",
                              "Dominant Fraction" ))

perm_list$Variable=factor(perm_list$Variable,
                          levels = c( "Interaction effect",
                                      "Ext. vs Int. N-Fert." ,
                            "CT vs MP Tillage"
                          ))

p1=ggplot(perm_list,aes(x=paste(Soil_Type, Year), y=Variable, fill=100*R2))+
  geom_tile(colour="black")+facet_wrap(~Type, ncol=1)+
  scale_fill_distiller(palette = "RdBu", name="Exp. Var (%)")+
  geom_text(aes(label=padj2), size=10)+
  xlab("")+
  ylab("")+
  theme_bw()+
  theme(strip.background=element_rect(fill="white",colour="white")) +
  theme(strip.text=element_text(size=25,colour="black")) +
  
  theme(axis.text.y=element_text(size=25,colour="black")) +
  theme(axis.text.x=element_text(size=25,colour="black")) +
  theme(axis.title.x=element_text(size=25,colour="black")) +
  
  theme(legend.text=element_text(size=25,colour="black")) + 
  theme(legend.title=element_text(size=25,colour="black")) + 
  theme(legend.position="top",axis.title.y=element_text(size=25,colour="black")) + 
  theme(legend.key.size=unit(2,"cm"))

````


```{r}
dir.create(file.path("../FigS6_permanovaplots"), showWarnings = FALSE)

png(filename = "../FigS6_permanovaplots/PERMANOVA_PLOTS_full_community_and_Dominant_fraction_in_three_years.png", height = 4000, width = 4000, res=300)
print(p1) 
dev.off()
```

```{r}
common_ones_pos_BS=as.data.frame(table(c(BS_pos_resp_2019$ASV,
                                         BS_pos_resp_2020$ASV,
                                         BS_pos_resp_2021$ASV)))%>%
  filter(Freq>2)
print(common_ones_pos_BS)

common_ones_neg_BS=as.data.frame(table(c((BS_neg_resp_2019$ASV),
                                         (BS_neg_resp_2020$ASV),
                                         (BS_neg_resp_2021$ASV))))%>%
  filter(Freq>2)

print(common_ones_neg_BS)

common_ones_pos_RH=as.data.frame(table(c(RH_pos_resp_2019$ASV,
                                         RH_pos_resp_2020$ASV,
                                         RH_pos_resp_2021$ASV)))%>%
  filter(Freq>2)
print(common_ones_pos_RH)

common_ones_neg_RH=as.data.frame(table(c((RH_pos_resp_2019$ASV),
                                         (RH_pos_resp_2020$ASV),
                                         (RH_pos_resp_2021$ASV))))%>%
  filter(Freq>2)

print(common_ones_neg_RH)

```

The End
```{r}
```
