
```{r,  results="hide"}
library(tidyverse)# Tidying up the data, Version 2.0.0
library(ggplot2) # Creating graphs, Version 3.5.1
library(plyr) # Tidying up data, Version 1.8.9
library(dplyr) #Tidying up data, Version 1.1.4
library(readr) # Loading text files, Version 2.1.5
library(readxl) # Loading excel files, Version 1.4.4
library(ggpubr) # Adding statistics in plots, Version 0.6.0 
library(stringi) # String selection tool, Version 1.8.4 
library(tidyr) # Tidying up the data, Version 1.3.1
library(reshape2) # Reshaping the data and infer statistics, Version 1.4.4
```

The script follows a further analysis of genome growth rates. 
Thus, in case anyone needs to re-run, you need to load this file 
```{r}
GRfiles=read.csv(file.path("../OutputData", "Resp_Tillage_GMs_Growth_rates_GenomeSize_CazymeGenes.csv"), check.names=F)
GRfiles= dcast(Soil_Type+till2+tax.Phylum+Genome+Year~.,  value.var = "DoublingTime", mean, data=GRfiles)%>%
  select(DoublingTime=".", everything())

```

Create the first plot
```{r}


plot1 = ggplot(GRfiles, 
  aes(fill=tax.Phylum, x=till2, y=log10(DoublingTime))) +
  geom_jitter(position = position_jitterdodge(jitter.width = 0.1,dodge.width = 1),size=3, shape=21) +
  geom_boxplot(position = position_dodge(width = 1), alpha=0.75) +
  scale_fill_brewer(palette = "Set3", name="") +
  theme_bw() +
  xlab("Tillage intensity") + 
  ylab("Log10 pmDT (hours)") +
  theme(strip.background=element_rect(fill="white", colour="white")) +
  theme(strip.text=element_text(size=35,colour="black",angle=0)) +

  theme(axis.text.y=element_text(size=35,colour="black")) +
  theme(axis.text.x=element_text(size=35,colour="black")) +
  theme(axis.title.x=element_text(size=35,colour="black")) +
  theme(axis.title.y=element_text(size=35,colour="black")) +
  
  theme(legend.title=element_text(size=35,colour="black")) +
  theme(legend.text=element_text(size=35,colour="black")) +
  theme(legend.key.size=unit(2,"cm"))

```

Create the second plot
```{r}
GRfiles=read.csv(file.path("../OutputData", "Resp_Tillage_GMs_Growth_rates_GenomeSize_CazymeGenes.csv"), check.names=F)

GRfiles$till2=GRfiles$coeff
GRfiles$till2[GRfiles$till2>0]="MP"
GRfiles$till2[GRfiles$till2!="MP"]="CT"
GRfiles1=dcast(GRfiles,Soil_Type+till2+tax.Phylum+Genome+Year+ASV~., value.var = "DoublingTime",mean)%>%
  select(lg=".", everything())
```

```{r}

GRfiles1$till3=ifelse(GRfiles1$till2 == "CT", 0, 1)
GRfiles1$lg=(GRfiles1$lg)



GRfilesB=filter(GRfiles1, Soil_Type=="BS")
GRfilesB=filter(GRfilesB, tax.Phylum%in%c("Actinobacteriota",
                                          "Firmicutes", 
                                          "Proteobacteria"))

# I modfied the plist after the selection of phyla
# Now it will provide to you both p-values and d
# for every phylum

plist=list()
for(j in unique(GRfilesB$tax.Phylum)){
  file1=filter(GRfilesB, tax.Phylum==paste0(j))  
  w1=wilcox.test(file1$lg~file1$till2)
  file2=dcast(Soil_Type~till2,  value.var = "lg", mean, data=file1)
  p=data.frame(p= w1$p.value,
  d=(file2$CT-file2$MP)/sd(file1$lg),
  Phylum=paste0(j))
  plist=rbind(plist, p)
}

plist$adj=p.adjust(plist$p, method = "BH")
#write.csv(plist, file = "Growth_rates_per_phylum_plist.csv")

plot2 = ggplot(GRfilesB, 
  aes(fill=till2, y=log10(lg), x=tax.Phylum)) +
  geom_jitter(position = position_jitterdodge(dodge.width = 1),shape=21, size=2) +
  geom_violin(alpha=0.5, position = position_dodge(width = 1)) +
    geom_boxplot(alpha=0.5, position = position_dodge(width = 1)) +

  facet_wrap(~tax.Phylum,scales = "free") +
  scale_fill_brewer(name="",palette = "Dark2") +
  theme_bw() +
  xlab("") +
  ylab("Log10 pmDT (hours)") +
  theme(strip.background=element_rect(fill="white",colour="white")) +
  theme(strip.text=element_text(size=18,colour="white",angle=0)) +
 
  theme(axis.text.y=element_text(size=35,colour="black")) +
  theme(axis.text.x=element_text(size=35,colour="black")) +
  theme(axis.title.x=element_text(size=35,colour="black")) +
  theme(axis.title.y=element_text(size=35,colour="black")) +
  
  theme(legend.title=element_text(size=35,colour="black")) +
  theme(legend.text=element_text(size=35,colour="black")) +
  theme(legend.key.size=unit(2,"cm")) + 
  
  stat_compare_means(method = "wilcox.test", hide.ns = T, label = "p.signif",size=8)


plot2B = ggplot(GRfilesB, 
  aes(fill=till2, y=log10(lg), x=as.factor(Year))) +
  geom_jitter(position = position_jitterdodge(dodge.width = 1),shape=21, size=2) +
  geom_violin(alpha=0.5, position = position_dodge(width = 1)) +
  geom_boxplot(alpha=0.5, position = position_dodge(width = 1)) +

  facet_wrap(~tax.Phylum,scales = "free") +
  scale_fill_brewer(name="",palette = "Dark2") +
  theme_bw() +
  xlab("") +
  ylab("Log10 pmDT (hours)") +
  theme(strip.background=element_rect(fill="white",colour="white")) +
  theme(strip.text=element_text(size=35,colour="black",angle=0)) +
 
  theme(axis.text.y=element_text(size=35,colour="black")) +
  theme(axis.text.x=element_text(size=35,colour="black")) +
  theme(axis.title.x=element_text(size=35,colour="black")) +
  theme(axis.title.y=element_text(size=35,colour="black")) +
  
  theme(legend.title=element_text(size=35,colour="black")) +
  theme(legend.text=element_text(size=35,colour="black")) +
  theme(legend.key.size=unit(2,"cm")) + 
  
  stat_compare_means(method = "wilcox.test", hide.ns = T,
                     label = "p.signif",size=8)

```  


```{r}
sizegenome=read.csv(file.path("../OutputData", "Resp_Tillage_GMs_Growth_rates_GenomeSize_CazymeGenes.csv")) 
```

```{r}
matches2=sizegenome
matches2$till2=matches2$coeff
matches2$till2[matches2$till2>0]="MP"
matches2$till2[matches2$till2!="MP"]="CT"
matches2=dcast(matches2,
Genome+till2+Soil_Type+tax.Phylum+Year+ASV~., value.var =  "Genome_Size2",mean)%>%
  select(Corrected_size=".", everything())
```

```{r}

GSfiles=filter(matches2, Soil_Type=="BS")
plot3= ggplot(GSfiles, 
  aes(fill=tax.Phylum, x=till2, y=(log10(Corrected_size)))) +
  geom_jitter(position = position_jitterdodge(jitter.width = 0.1,dodge.width = 1),size=3, shape=21) +
  geom_boxplot(position = position_dodge(width = 1), alpha=0.75) +
  scale_fill_brewer(palette = "Set3", name="") +
  theme_bw() +
  xlab("Tillage intensity") + 
  ylab("Log10 genome size (bp)") +
  theme(strip.background=element_rect(fill="white",colour="white")) +
  theme(strip.text=element_text(colour="black",size=35,angle=0)) +
  
  theme(axis.text.y=element_text(size=35,colour="black")) +
  theme(axis.text.x=element_text(size=35,colour="black")) +
  theme(axis.title.x=element_text(size=35,colour="black")) +
  theme(axis.title.y=element_text(size=35,colour="black")) +
  
  theme(legend.title=element_text(size=35,colour="black")) +
  theme(legend.text=element_text(size=35,colour="black")) +
  theme(legend.key.size=unit(2,"cm"))

```
```{r}
GSfiles2B=filter(GSfiles, tax.Phylum%in%c("Actinobacteriota",
                                          "Firmicutes", 
                                          "Proteobacteria"))

plist=list()
GSfiles2B$GS=log10(GSfiles2B$Corrected_size)
for(j in unique(GSfiles2B$tax.Phylum)){
  file1=filter(GSfiles2B, tax.Phylum==paste0(j))  
  w1=wilcox.test(file1$GS~file1$till2)
  file2=dcast(Soil_Type~till2,  value.var = "GS", mean, data=file1)
  p=data.frame(p= w1$p.value,
  d=(file2$CT-file2$MP)/sd(file1$GS),
  Phylum=paste0(j))
  plist=rbind(plist, p)
  }
plist$adj=p.adjust(plist$p, method = "BH")
#write.csv(plist, file = "GenomeSize_per_phylum_plist.csv")

plot4= ggplot(GSfiles2B, 
  aes(fill=till2, y=(GS), x=tax.Phylum)) +
  geom_jitter(position = position_jitterdodge(dodge.width = 1),shape=21, size=2) +
   geom_violin(alpha=0.5, position = position_dodge(width = 1)) +
    geom_boxplot(alpha=0.5, position = position_dodge(width = 1)) +
  facet_wrap(~tax.Phylum,scales = "free") +
  scale_fill_brewer(name="",palette = "Dark2") +
  theme_bw() +
  xlab("") +
  ylab("Log10 genome size (bp)") +
  theme(strip.background=element_rect(fill="white",colour="white")) +
  theme(strip.text=element_text(size=18,colour="white",angle=0)) +

  theme(axis.text.y=element_text(size=35,colour="black")) +
  theme(axis.text.x=element_text(size=35,colour="black")) +
  theme(axis.title.x=element_text(size=35,colour="black")) +
  theme(axis.title.y=element_text(size=35,colour="black")) +
  
  theme(legend.title=element_text(size=35,colour="black")) +
  theme(legend.text=element_text(size=35,colour="black")) +
  theme(legend.key.size=unit(2,"cm")) +
  
  stat_compare_means(method = "wilcox.test", hide.ns = T, label = "p.signif",size=8)


plot4B = ggplot(GSfiles2B, 
  aes(fill=till2, y=(GS), x=as.factor(Year))) +
  geom_jitter(position = position_jitterdodge(dodge.width = 1),shape=21, size=2) +
  geom_violin(alpha=0.5, position = position_dodge(width = 1)) +
  geom_boxplot(alpha=0.5, position = position_dodge(width = 1)) +

  facet_wrap(~tax.Phylum,scales = "free") +
  scale_fill_brewer(name="",palette = "Dark2") +
  theme_bw() +
  xlab("") +
  ylab("Log10 genome size (bp)") +
  theme(strip.background=element_rect(fill="white",colour="white")) +
  theme(strip.text=element_text(size=35,colour="black",angle=0)) +
 
  theme(axis.text.y=element_text(size=35,colour="black")) +
  theme(axis.text.x=element_text(size=35,colour="black")) +
  theme(axis.title.x=element_text(size=35,colour="black")) +
  theme(axis.title.y=element_text(size=35,colour="black")) +
  
  theme(legend.title=element_text(size=35,colour="black")) +
  theme(legend.text=element_text(size=35,colour="black")) +
  theme(legend.key.size=unit(2,"cm")) + 
  
  stat_compare_means(method = "wilcox.test", hide.ns = T, label = "p.signif",size=8)

```

```{r}
cazygenes= read.csv(file = "../OutputData/Resp_Tillage_GMs_Growth_rates_GenomeSize_CazymeGenes.csv")
```
Until this part can not be uploaded in the linux server 

```{r}

cazygenes2=cazygenes
cazygenes2=filter(cazygenes2, Soil_Type=="BS")

plot5 = ggplot(cazygenes2, 
  aes(fill=tax.Phylum, x=till2, y=(log10( CazymeGenes+1)))) +
  geom_jitter(position = position_jitterdodge(jitter.width = 0.1,dodge.width = 1),size=3, shape=21) +
  geom_violin(alpha=0.5, position = position_dodge(width = 1)) +
    geom_boxplot(alpha=0.5, position = position_dodge(width = 1)) +

  scale_fill_brewer(palette = "Set3", name="") +
  theme_bw() +
  xlab("Tillage intensity") + 
  ylab("Log10 (CAZyme genes/genome)") +
  theme(strip.background=element_rect(fill="white",colour="white")) +
  theme(strip.text=element_text(size=35,colour="black",angle=0)) +

  theme(axis.text.y=element_text(size=35,colour="black")) +
  theme(axis.text.x=element_text(size=35,colour="black")) +
  theme(axis.title.x=element_text(size=35,colour="black"))+
  theme(axis.title.y=element_text(size=35,colour="black"))+
  
  theme(legend.title=element_text(size=35,colour="black"))+
  theme(legend.text=element_text(size=35,colour="black"))+
  theme(legend.key.size=unit(2,"cm"))

cazygenes3=filter(cazygenes2, tax.Phylum%in%c("Actinobacteriota", "Firmicutes", "Proteobacteria"))


```

```{r}
plist=list()
cazygenes3$SG=log10(cazygenes3$CazymeGenes)
for(j in unique(cazygenes3$tax.Phylum)){
  file1=filter(cazygenes3, tax.Phylum==paste0(j))  
  w1=wilcox.test(file1$SG~file1$till2)
  file2=dcast(Soil_Type~till2,  value.var = "SG", mean, data=file1)
  p=data.frame(p= w1$p.value,
  d=(file2$CT-file2$MP)/sd(file1$SG),
  Phylum=paste0(j))
  plist=rbind(plist, p)
}

plist$adj=p.adjust(plist$p, method = "BH")
#write.csv(plist, file = "CAZY_no_per_phylum_plist.csv")


plot6= ggplot(cazygenes3, 
  aes(fill=till2, y=log10(CazymeGenes+1), x=tax.Phylum)) +
  geom_jitter(position = position_jitterdodge(dodge.width = 1),shape=21, size=2)+
geom_violin(alpha=0.5, position = position_dodge(width = 1)) +
  geom_boxplot(alpha=0.5, position = position_dodge(width = 1)) +
  facet_wrap(~tax.Phylum,scales = "free") +
  scale_fill_brewer(name="",palette = "Dark2") +
  theme_bw() +
  xlab("") +
  ylab("Log10 (CAZyme genes/genome)") +
  theme(strip.background=element_rect(fill="white", colour="white")) +
  theme(strip.text=element_text(size=18,colour="white",angle=0)) +
  
  theme(axis.text.y=element_text(size=35,colour="black")) +
  theme(axis.text.x=element_text(size=35,colour="black")) +
  theme(axis.title.x=element_text(size=35,colour="black")) +
  theme(axis.title.y=element_text(size=35,colour="black")) +
  
  theme(legend.title=element_text(size=35,colour="black")) +
  theme(legend.text=element_text(size=35,colour="black")) +
  theme(legend.key.size=unit(2,"cm")) +  
  
  stat_compare_means(method = "wilcox.test", hide.ns = T, label = "p.signif",size=8)




plot6B= ggplot(cazygenes3, 
  aes(fill=till2, y=log10(CazymeGenes+1), x=as.factor(Year))) +
  geom_jitter(position = position_jitterdodge(dodge.width = 1),
              shape=21, size=2) +
  geom_violin(alpha=0.5, position = position_dodge(width = 1)) +
  geom_boxplot(alpha=0.5, position = position_dodge(width = 1)) +

  facet_wrap(~tax.Phylum,scales = "free") +
  scale_fill_brewer(name="",palette = "Dark2") +
  theme_bw() +
  xlab("") +
  ylab("Log10 (CAZyme genes/genome)") +
  theme(strip.background=element_rect(fill="white",colour="white")) +
  theme(strip.text=element_text(size=35,colour="black",angle=0)) +
 
  theme(axis.text.y=element_text(size=35,colour="black")) +
  theme(axis.text.x=element_text(size=35,colour="black")) +
  theme(axis.title.x=element_text(size=35,colour="black")) +
  theme(axis.title.y=element_text(size=35,colour="black")) +
  
  theme(legend.title=element_text(size=35,colour="black")) +
  theme(legend.text=element_text(size=35,colour="black")) +
  theme(legend.key.size=unit(2,"cm")) + 
  
  stat_compare_means(method = "wilcox.test", hide.ns = T,
                     label = "p.signif",size=8)

```
Counting genomes
```{r}
Genome_Count_Per_Phylum=data.frame(No=table(paste0(
  GRfiles$tax.Phylum,"_",GRfiles$till2, GRfiles$Soil_Type)))

```




Combine plots
```{r}
plots=ggarrange(plot2,plot4,plot6,  common.legend = T,
  labels = c("A)","B)","C)"),
  font.label = list(face="bold", size=25),ncol =  1)
  
```

Save plot
```{r}
png(filename = "Fig5_Phylum.png", height = 4500,
    width = 3000, res=200)
print(plots)
dev.off()
```
```{r}
print("The End")
```
