```{r}
library(tidyverse)
library(ggplot2)
library(plyr)
library(dplyr)
library(readr)
library(readxl)
library(ggpubr)
library(stringi)
library(tidyr)
library(reshape2)
library(vegan)
library(parallel)
library(lme4)
library(ggtext)
library(boot)
library(car)
library(dunn.test)
library(multcompView)
```

Upload the nutrient table
```{r}
nutrients1=read.csv(file.path("../InputData", "soil_lab.csv"), check.names=F)
```

Change the names of the variable accordingly 
```{r}
nutrients1$TILLAGE2=nutrients1$Tillage
nutrients1$FERTILIZATION2=nutrients1$Fertilization
nutrients1$TILLAGE2=ifelse(nutrients1$TILLAGE2 == "Cultivator", 0, 1)
nutrients1$FERTILIZATION2=ifelse(nutrients1$FERTILIZATION2 == "extensive", 0, 1)
```

prepare the nutrients data for our model 
```{r}
rownames(nutrients1)=paste0(nutrients1$TILLAGE2,"_",
                             nutrients1$FERTILIZATION2,"_",
                             nutrients1$Block,"_",
                             nutrients1$Experimental_Year)
nutrients1=as.data.frame(nutrients1)
nutrients2=nutrients1[rownames(nutrients1),6:21, drop=F]
nutrients2=as.data.frame(apply(nutrients2, 2, function(x) replace(x, is.na(x), mean(x, na.rm = TRUE))))
nutrients2=(nutrients2)
nutrients1[rownames(nutrients1),6:21]=nutrients2
nutrients3=gather(nutrients1,
  -c(colnames(nutrients1[rownames(nutrients1),
  c(1:5, 22:ncol(nutrients1))])),
  key ="Nutrient",
  value = "Variable")

nutrients4= nutrients3 %>% filter(Nutrient %in% c("N[%]", "OM[%]"))
nutrients4$G=paste0(nutrients4$Tillage,";", nutrients4$Fertilization)

nutrients4$Nutrient=gsub("OM\\[%\\]","SOM (%)",
  gsub("N\\[%\\]", "N (%)", nutrients4$Nutrient)
)
```
Tukey's test for Nitrogen and Carbon 
```{r}
Letter_list=list()
results_list <- list()
for(i in unique(nutrients4$Nutrient)){
  for(j in unique(nutrients4$Experimental_Year)){
  
    file1=filter(nutrients4, Nutrient==i & Experimental_Year==j)
    
    anova_result = aov(Variable~G, data=file1)
    
    residuals <- residuals(anova_result)
    shapiro_test <- shapiro.test(residuals)
    results_list[[paste(i, j, sep = "_")]] <- list(
      ANOVA = summary(anova_result),
      Shapiro = shapiro_test
    )
    
    print(paste("Shapiro-Wilk Test for Nutrient:", i, "Year:", j))
    print(shapiro_test)
    
    tukey_result = TukeyHSD(anova_result)
    tukey_comparisons = as.data.frame(tukey_result$G)
    tukey_comparisons$row = rownames(tukey_comparisons)
    tukey_comparisons = tukey_comparisons %>%separate(row, into = c("row", "col"), sep = "-") %>%select(row, col, `p adj`)
    
    orderlist = aggregate(file1$Variable, by = list(file1$G), FUN = mean)
    colnames(orderlist) = c("G", "Variable")
    
    
    comparisons = full_join(tukey_comparisons, orderlist %>% mutate(row = G), by = "row") %>% na.omit()
    comparisons=comparisons[order(comparisons$Variable, decreasing = T),]
    names1=paste0(comparisons$row,"-", comparisons$col)
    p=comparisons$p
    names(p)=names1
    letters=multcompView::multcompLetters(p, compare="<", reversed=F)$Letters%>%as.data.frame()
    colnames(letters)="L1"
    letters$G=rownames(letters)
    letters$Experimental_Year=j
    letters$Nutrient=paste0(i)
    Letter_list=rbind(letters, Letter_list)  
  }
}

```


Plot the Soil and Nitrogen concentrations.
```{r}

nutrients4$Tillage=gsub("Cultivator","CT",
  gsub("Plough", "MP", nutrients4$Tillage)
)
nutrients4$Fertilization=gsub("extensive","Ext.",
  gsub("intensive", "Int.", nutrients4$Fertilization)
)

nutrients5<-dcast(nutrients4, Experimental_Year+Tillage+G+Fertilization+Nutrient~., 
                  value.var =  "Variable", mean)%>%select(Variable=".",
                                             everything())%>%full_join(Letter_list)


plot1 = ggplot(data=nutrients5, 
           aes(x = as.factor(Experimental_Year), y=Variable, fill=paste0(Tillage,"-",Fertilization))) +
  geom_bar( colour="black",
           stat="summary", position=position_dodge(width=0.9), alpha=0.6) +
  geom_point(data=nutrients4, 
             aes(x=as.factor(Experimental_Year), y=Variable, fill=paste0(Tillage,"-",Fertilization)), 
             position=position_jitterdodge (jitter.width=0.25,
                                            dodge.width =0.9 ), shape=21,
             alpha=0.7, size=4) +
  facet_wrap(~Nutrient, strip.position="left", scales="free", labeller=label_value) +
  scale_alpha_manual(values = c(1, 0.1), name="N. Fert.: ") +
  scale_fill_manual(values = c("#c8e9df","#4ab795", "#fdb79c",  "#fb6328"), name="") +
  theme_bw() +
  ylab("") +
  xlab("") +
  theme(strip.background=element_rect(fill="white", colour="white"), strip.placement = "outside") +
  theme(strip.text=element_text(size=25,colour="black")) +
  
  theme(axis.text.x=element_text(size=25,colour="black")) +
  theme(axis.text.y=element_text(size=25,colour="black")) +
  theme(axis.title.x=element_text(size=25,colour="black")) +
  
  theme(legend.text=element_text(size=25,colour="black")) + 
  theme(legend.title=element_text(size=25,colour="black")) + 
  theme(legend.position="top",axis.title.y=element_text(size=25,colour="black")) + 
  theme(legend.key.size=unit(2,"cm")) +

  guides(alpha = guide_legend(override.aes = list(fill="black")))+
    geom_text(stat = "summary", 
aes(y=Variable*1.1, label=L1), size=9, position = position_dodge(width = 1))
```

Create the linear model with year as fixed effect 

```{r}
fixed_effects=list()
for(i in unique(paste0(nutrients4$Nutrient))){
  file1=dplyr::filter(nutrients4, Nutrient==paste0(i)) 
  file1$G=paste0(file1$Fertilization,";",file1$Tillage)
  file1$Experimental_Year=as.numeric(file1$Experimental_Year) - 2018
  file1$Variable=scale(file1$Variable)
  # Add p_value for the model with Experimental_Year as fixed effect
  file2_fixed=lm(Variable~TILLAGE2*FERTILIZATION2*Experimental_Year, data=file1)
  print(file2_fixed)
    filename1= paste0("../FigS1_QQPlot", "/QQ_Plots_",gsub(" .%.","",i),".png")
    png(filename1, width = 1200, height = 600)
    
      qqnorm(resid(file2_fixed), main=paste("Normal Q-Q Plot for",i))
      qqline(resid(file2_fixed), col="red")
     
    dev.off()

  #Apply Bootstrap for inferring p-values and 95% CI
  boot.out = Boot(file2_fixed, f=coef, method="residual", R=10000)#, ncores = 25) # Use only if you have a multicore Linux system.
  print("Boot  finished")
    
  CI.lower = apply(boot.out$t, 2, function(x) as.numeric(quantile(x, probs=.025, na.rm=TRUE)))
  CI.upper = apply(boot.out$t, 2, function(x) as.numeric(quantile(x, probs=.975, na.rm=TRUE)))
  results_df = as.data.frame(summary(boot.out))
  p = rbind(
      (1-apply(boot.out$t<0, 2, mean))*2,
      (1-apply(boot.out$t>0, 2, mean))*2)
  pvalues=data.frame(pval= apply(p, 2, min))
  results_df2=cbind(results_df, pvalues, lower=CI.lower, upper=CI.upper)
  results_df2$Nutrient=paste0(i)
  fixed_effects=rbind(results_df2%>%rownames_to_column(var = "Variable"),fixed_effects)  
}

fixed_effects2=filter(fixed_effects,
                      Variable!="(Intercept)")

fixed_effects2$pval[fixed_effects2$pval<0.05]="*p* < 0.05"
fixed_effects2$pval[fixed_effects2$pval!="*p* < 0.05"]="*p* > 0.05"
```

Create the plot for Year as random effect 
```{r}
fixed_effects2$Variable=gsub(":",
  " x ",fixed_effects2$Variable)

fixed_effects2$Variable=gsub("FERTILIZATION2",
  "Ext. vs Int. N-fert.",
  gsub("TILLAGE2", "CT vs MP tillage", fixed_effects2$Variable)
)

fixed_effects2$Variable=gsub("Experimental_Year",
  "Experimental year",fixed_effects2$Variable
  )

```

```{r}  
plot2 =ggplot(fixed_effects2, 
  aes(y=Variable, x=bootMed, fill=pval)) +
  geom_pointrange(shape=21, size=3, aes(xmax=upper, xmin= lower)) +
  facet_wrap(~Nutrient, scales="fixed", ncol=1) +
  scale_fill_manual(values = c("#f1a340","#f7f7f7"), name="p-value") +
  theme_bw() +
  ylab("") +
  xlab("LM: β1-Coef.± 95%CI") +
  theme(strip.background=element_rect(fill="white",colour="black")) +
  theme(strip.text=element_text(size=25,colour="black")) +
  
  theme(axis.text.y=element_text(size=25,colour="black")) +
  theme(axis.text.x=element_text(size=25,colour="black")) +
  theme(axis.title.x=element_text(size=25,colour="black")) +
  
  theme(legend.text=element_text(size=25,colour="black")) + 
  theme(legend.title=element_text(size=25,colour="black")) + 
  theme(legend.position="top",axis.title.y=element_text(size=25,colour="black")) + 
  theme(legend.key.size=unit(2,"cm")) +
  theme(legend.text=element_markdown()) +
  
  geom_vline(xintercept=0, linetype=2) 

```

Save the image
```{r}
png(filename = "Fig1_SoilLab.png",
    width = 5000, 
    height = 7000, 
    res=300)
print(ggarrange(plot1, plot2,
                labels = c("A)","B)"), ncol = 1,
                font.label = list(size = 24)))
dev.off()
```

Save the rest of the data as SI table.
```{r}
write.csv(file = file.path("../OutputData", "TableS2_SoilLab.csv"), filter(fixed_effects2, Variable!="(Intercept)"))
```

```{r}
print(paste0("The end!!!"))
```